n1 = float(input('Primeira nota do aluno: '))
n2 = float(input('Segunda nota do aluno: '))
n3 = float(input('Terceira nota do aluno: '))
n4 = float(input('Quarta nota do aluno: '))
print('A média do aluno é {:.1f}: '.format((n1 + n2 + n3 + n4) / 4))