a = input('Digite algo:')
print('O tipo primitivo desse valor é:', type(a))
print('Tem espaços?', a.isspace())
print('Tem código alfa?', a.isalpha())
print('É numérico?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maiúscula?', a.isupper())
print('Está em minúscula?', a.islower())
print('Está capitalizado?', a.istitle())

